"""CustomerPolicy table update

Revision ID: f79bb1e17ab3
Revises: e7de6c2d4d99
Create Date: 2024-12-06 10:21:17.073819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79bb1e17ab3'
down_revision: Union[str, None] = 'e7de6c2d4d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_policy',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=False),
    sa.Column('date_assigned', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policy.policy_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('policy_customer_id_fkey', 'policy', type_='foreignkey')
    op.drop_column('policy', 'customer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('policy', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('policy_customer_id_fkey', 'policy', 'customer', ['customer_id'], ['customer_id'])
    op.drop_table('customer_policy')
    # ### end Alembic commands ###
